@page "/products/deletar/{id:int}"
@inject Context _context
@inject NavigationManager _navigationManager

<div class="mb-3">
    <h3 class="titulo text-center text-white border-5 p-3 bg-primary justify-content-center">Deletar Produto</h3>
    <p class="alert alert-danger">Você irá deletar o produto: @_model?.Title</p>
</div>


<EditForm Model="@_model" OnValidSubmit="SubmitAsync">

    <DataAnnotationsValidator />
    <ValidationSummary class="alert-danger" />

    <div class="mb-3">
        <label class="text-muted form-label" for="Title">Título</label>
        <InputText readonly class="form-control" type="text" id="Title" @bind-Value="_model.Title" />
    </div>

    <div class="mb-3">
        <label class="text-muted form-label" for="Price">Preço</label>
        <InputNumber readonly class="form-control" type="number" id="Price" @bind-Value="_model.Price" />
    </div>

    @if (!string.IsNullOrEmpty(_errorMsg))
    {
        <div class="alert alert-danger" role="alert">
            @_errorMsg
        </div>
    }

    <button class="btn btn-danger" type="submit">Deletar</button>
    <a href="/" class="btn btn-dark">Voltar</a>
</EditForm>




@code {
    [Parameter]
    public int Id { get; set; }

    private Product? _model = new();
    private List<Category> _categories = new();
    string? _errorMsg = null;

    protected override async Task OnInitializedAsync()
    {
       _model = await _context.Products.AsNoTracking().FirstOrDefaultAsync(x => x.Id == Id);
    }

    private async Task SubmitAsync()
    {
        try
        {
            var prod = await _context.Products.FirstOrDefaultAsync(x => x.Id == Id);
            if (prod is null)
            {
                throw new Exception("Produto não encontrado");
            }
            prod.Title = _model.Title;
            prod.Price = _model.Price;
            prod.CategoryId = _model.CategoryId;

            _context.Products.Remove(prod);
            await _context.SaveChangesAsync();

            _navigationManager.NavigateTo("/products");
        }
        catch (Exception ex)
        {
            _errorMsg = ex.Message;
        }
    }

}
